// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMwDO_HjpuN2Qp8qXRTI71iLhSXvLwHI',
    appId: '1:711275002951:web:804e0e99b98096a8690562',
    messagingSenderId: '711275002951',
    projectId: 'atc1-e2006',
    authDomain: 'atc1-e2006.firebaseapp.com',
    storageBucket: 'atc1-e2006.firebasestorage.app',
    measurementId: 'G-2SNG5GDEV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCI05QqFSs3rIex8-R0Hbkv8ttw3LHzCE',
    appId: '1:711275002951:android:549be2adc9802471690562',
    messagingSenderId: '711275002951',
    projectId: 'atc1-e2006',
    storageBucket: 'atc1-e2006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jBhBpDdFL7fBC9GArdqtRSqKYx7Rttc',
    appId: '1:711275002951:ios:75f3c2ae96c7278c690562',
    messagingSenderId: '711275002951',
    projectId: 'atc1-e2006',
    storageBucket: 'atc1-e2006.firebasestorage.app',
    iosBundleId: 'com.example.masari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jBhBpDdFL7fBC9GArdqtRSqKYx7Rttc',
    appId: '1:711275002951:ios:75f3c2ae96c7278c690562',
    messagingSenderId: '711275002951',
    projectId: 'atc1-e2006',
    storageBucket: 'atc1-e2006.firebasestorage.app',
    iosBundleId: 'com.example.masari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBejPRVUO5KYOPJB2Zdd1LTxio2nLH8iyM',
    appId: '1:711275002951:web:5979925db051ae42690562',
    messagingSenderId: '711275002951',
    projectId: 'atc1-e2006',
    authDomain: 'atc1-e2006.firebaseapp.com',
    storageBucket: 'atc1-e2006.firebasestorage.app',
    measurementId: 'G-T0PTB3W4QS',
  );
}
